version: 0.2

phases:
  install:
    commands:
      - echo "updating packages"
      - yum update -y
      - echo "Installing python"
      - yum install -y python3 python3-pip
      - python3 --version

  build:
    commands:
      - echo "Running python script for verification"
      - python3 Python-app/src/hello.py

artifacts:
  files:
    - Python-app/appspec.yml
    - Python-app/scripts/**/*
    - Python-app/src/**/*

  discard-paths: no
