version: 0.2

phases:
  install:
    commands:
      - echo "Updating packages"
      - yum update -y
      - echo "Installing Python"
      - yum install -y python3 python3-pip
      - python3 --version
      - echo "Installing flake8 linter"
      - pip3 install flake8

  pre_build:
    commands:
      - echo "Running flake8 lint checks"
      - flake8 Python-app/src
  build:
    commands:
      - echo "Running python script for verification"
      - python3 Python-app/src/hello.py
      - echo "Creating deployment zip artifact"
      - cd Python-app
      - zip -r ../Python-app.zip appspec.yml scripts src
      - cd ..

artifacts:
  files:
    - Python-app.zip
